---

sudo: false  # Use container-based infrastructure

branches:
  only:
    - master

language: python

matrix:
  include:
    - python: 3.6
      addons:
        apt:
          sources:
            - debian-sid    # Grab shellcheck from the Debian repo (o_O)

cache:
  apt: true
  bundler: true
  ccache: true
  custom_install: true  # Since we override the default install command.
  pip: true
  directories:
    - "${HOME}/.cache/pip"
    - "${HOME}/.ccache"
    - "${HOME}/.pip-cache"
    - "${VIRTUAL_ENV}"

before_cache:
  - ci/travis.before_cache.sh

before_install:
  - travis_retry rvm install 2.3.2 && rvm --default use 2.3.2
  - ci/travis.before_install.sh

install:
  - ci/travis.install.sh

script:
  - ci/travis.script.sh

notifications:
  slack:
    # yamllint disable-line rule:line-length
    secure: PDtcvz//in9jj9g96rjAePhb59NizHGxrPZpmVXvYLNuYh2iN4i9GgBruLoySS5pg4cALgs69quof9c6lF8U75w0FfcOxfANb+6Y5Joh/uvR7IhPe9rZjadsXG4kNlSwfTcxMOc9mTHmyKi50WcnwWGVjPAU8uKnlUPxV3K3kjeuKD6QDOJuCtKgTKyeW92VvtMAKILBD+UOrkdr72eCwtQ+cReQ2JNgYndRgjcs6TxDRAq2OISrHSyX7/ISfqvHcOCnH8jazSFYbYcTZ7Sk9CnDGt+FDz+e8hNysI5T8sFGge6eiwyJQ7ivqdvbWYKS0AFeJA8BQwbrA7gt6jLaM5v5WLY7npVMAhkwtM2s6/Z2p1IsEqhaigoLINfyBw6MCbIDeZg1OJdocuWRNE+pfZgVXzC2XXcnbg+u5ChaqgqoKqN3/Y+W0IGZ4AXXWcT1XHVgB414j4TZ+t/bIlKMbcdD4n9tvmV9+zm+bZ8keFkWlMSac4bW7wX9gOQG4FMUGolznTinwlAwpCpjP22gM7M6BoDwg2URWE5qcXoJYERHdsvaOAOTlj3RnnBjsVZwbIfk2gbWmE0aKwk8l21PBhjiBsZvHPyBR6EeAUi8bktQUfdAImk53h0GYPeSJ6ocu8fas8NgBuZf5Ysc0RxQYnQUkqZZBO53BOScDr87tHE=
